### ISSUE TITLE
Decide on choice of database

### ISSUE THREAD

**Issue by nhuntwalker** [StayWokeOrg/collateral-consequence#4]

**Comment by SeleniumK** [comment]
I am inclined to use postgres, but what are everyone's thoughts?

**Comment by rubinovitz** [comment]
I'm probably going to end up more on the front-end of this project so my
vote counts less, but :+1 postgres.
ᐧ

**Comment by clayote** [comment]
+1 postgres

**Comment by nhuntwalker** [comment]
Postgres it is!
